#set(CMAKE_AUTOUIC ON)
QT       += core gui sql

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17
INCLUDEPATH += src

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    src/backup.cpp \
    src/batch.cpp \
src/connection.cpp \
src/functions.cpp \
    src/macroformatdialog.cpp \
    src/macroinputdialog.cpp \
src/main.cpp \
src/mainwindow.cpp \
    src/restore.cpp \
src/sql.cpp \
src/sqlhighlighter.cpp \
src/statistics.cpp \
src/structure.cpp \
src/tunnelsqlmanager.cpp \
    src/two_checkbox_delegate.cpp \
src/users.cpp

HEADERS += \
    src/backup.h \
    src/batch.h \
src/connection.h \
src/functions.h \
    src/macroformatdialog.h \
    src/macroinputdialog.h \
src/mainwindow.h \
    src/restore.h \
src/sql.h \
src/sqlhighlighter.h \
src/statistics.h \
src/structure.h \
src/tunnelsqlmanager.h \
    src/two_checkbox_delegate.h \
    src/two_checkbox_list_model.h \
src/users.h

FORMS += \
    src/batch.ui \
src/connection.ui \
src/mainwindow.ui \
src/sql.ui \
src/statistics.ui \
src/structure.ui \
src/users.ui

TRANSLATIONS += \
    SequelFast_pt_BR.ts
CONFIG += lrelease
CONFIG += embed_translations
CONFIG += app_bundle # (This is the default, so this line is often omitted)

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

RESOURCES += \
    icons.qrc \
    themes/dark/darkstyle.qrc \
    themes/light/lightstyle.qrc
RESOURCES += themes/dark/darkstyle.qrc
RESOURCES += themes/light/lightstyle.qrc

# Ícone do executável no Windows
win32 {
    RC_FILE = icons/app_icon.rc
}

# Ícone do app no macOS
mac {
    ICON = resources/icon.icns

}

DISTFILES += \
    themes/dark/darkstyle.qss \
    themes/dark/rc/arrow_down.png \
    themes/dark/rc/arrow_down@2x.png \
    themes/dark/rc/arrow_down_disabled.png \
    themes/dark/rc/arrow_down_disabled@2x.png \
    themes/dark/rc/arrow_down_focus.png \
    themes/dark/rc/arrow_down_focus@2x.png \
    themes/dark/rc/arrow_down_pressed.png \
    themes/dark/rc/arrow_down_pressed@2x.png \
    themes/dark/rc/arrow_left.png \
    themes/dark/rc/arrow_left@2x.png \
    themes/dark/rc/arrow_left_disabled.png \
    themes/dark/rc/arrow_left_disabled@2x.png \
    themes/dark/rc/arrow_left_focus.png \
    themes/dark/rc/arrow_left_focus@2x.png \
    themes/dark/rc/arrow_left_pressed.png \
    themes/dark/rc/arrow_left_pressed@2x.png \
    themes/dark/rc/arrow_right.png \
    themes/dark/rc/arrow_right@2x.png \
    themes/dark/rc/arrow_right_disabled.png \
    themes/dark/rc/arrow_right_disabled@2x.png \
    themes/dark/rc/arrow_right_focus.png \
    themes/dark/rc/arrow_right_focus@2x.png \
    themes/dark/rc/arrow_right_pressed.png \
    themes/dark/rc/arrow_right_pressed@2x.png \
    themes/dark/rc/arrow_up.png \
    themes/dark/rc/arrow_up@2x.png \
    themes/dark/rc/arrow_up_disabled.png \
    themes/dark/rc/arrow_up_disabled@2x.png \
    themes/dark/rc/arrow_up_focus.png \
    themes/dark/rc/arrow_up_focus@2x.png \
    themes/dark/rc/arrow_up_pressed.png \
    themes/dark/rc/arrow_up_pressed@2x.png \
    themes/dark/rc/base_icon.png \
    themes/dark/rc/base_icon@2x.png \
    themes/dark/rc/base_icon_disabled.png \
    themes/dark/rc/base_icon_disabled@2x.png \
    themes/dark/rc/base_icon_focus.png \
    themes/dark/rc/base_icon_focus@2x.png \
    themes/dark/rc/base_icon_pressed.png \
    themes/dark/rc/base_icon_pressed@2x.png \
    themes/dark/rc/branch_closed.png \
    themes/dark/rc/branch_closed@2x.png \
    themes/dark/rc/branch_closed_disabled.png \
    themes/dark/rc/branch_closed_disabled@2x.png \
    themes/dark/rc/branch_closed_focus.png \
    themes/dark/rc/branch_closed_focus@2x.png \
    themes/dark/rc/branch_closed_pressed.png \
    themes/dark/rc/branch_closed_pressed@2x.png \
    themes/dark/rc/branch_end.png \
    themes/dark/rc/branch_end@2x.png \
    themes/dark/rc/branch_end_disabled.png \
    themes/dark/rc/branch_end_disabled@2x.png \
    themes/dark/rc/branch_end_focus.png \
    themes/dark/rc/branch_end_focus@2x.png \
    themes/dark/rc/branch_end_pressed.png \
    themes/dark/rc/branch_end_pressed@2x.png \
    themes/dark/rc/branch_line.png \
    themes/dark/rc/branch_line@2x.png \
    themes/dark/rc/branch_line_disabled.png \
    themes/dark/rc/branch_line_disabled@2x.png \
    themes/dark/rc/branch_line_focus.png \
    themes/dark/rc/branch_line_focus@2x.png \
    themes/dark/rc/branch_line_pressed.png \
    themes/dark/rc/branch_line_pressed@2x.png \
    themes/dark/rc/branch_more.png \
    themes/dark/rc/branch_more@2x.png \
    themes/dark/rc/branch_more_disabled.png \
    themes/dark/rc/branch_more_disabled@2x.png \
    themes/dark/rc/branch_more_focus.png \
    themes/dark/rc/branch_more_focus@2x.png \
    themes/dark/rc/branch_more_pressed.png \
    themes/dark/rc/branch_more_pressed@2x.png \
    themes/dark/rc/branch_open.png \
    themes/dark/rc/branch_open@2x.png \
    themes/dark/rc/branch_open_disabled.png \
    themes/dark/rc/branch_open_disabled@2x.png \
    themes/dark/rc/branch_open_focus.png \
    themes/dark/rc/branch_open_focus@2x.png \
    themes/dark/rc/branch_open_pressed.png \
    themes/dark/rc/branch_open_pressed@2x.png \
    themes/dark/rc/checkbox_checked.png \
    themes/dark/rc/checkbox_checked@2x.png \
    themes/dark/rc/checkbox_checked_disabled.png \
    themes/dark/rc/checkbox_checked_disabled@2x.png \
    themes/dark/rc/checkbox_checked_focus.png \
    themes/dark/rc/checkbox_checked_focus@2x.png \
    themes/dark/rc/checkbox_checked_pressed.png \
    themes/dark/rc/checkbox_checked_pressed@2x.png \
    themes/dark/rc/checkbox_indeterminate.png \
    themes/dark/rc/checkbox_indeterminate@2x.png \
    themes/dark/rc/checkbox_indeterminate_disabled.png \
    themes/dark/rc/checkbox_indeterminate_disabled@2x.png \
    themes/dark/rc/checkbox_indeterminate_focus.png \
    themes/dark/rc/checkbox_indeterminate_focus@2x.png \
    themes/dark/rc/checkbox_indeterminate_pressed.png \
    themes/dark/rc/checkbox_indeterminate_pressed@2x.png \
    themes/dark/rc/checkbox_unchecked.png \
    themes/dark/rc/checkbox_unchecked@2x.png \
    themes/dark/rc/checkbox_unchecked_disabled.png \
    themes/dark/rc/checkbox_unchecked_disabled@2x.png \
    themes/dark/rc/checkbox_unchecked_focus.png \
    themes/dark/rc/checkbox_unchecked_focus@2x.png \
    themes/dark/rc/checkbox_unchecked_pressed.png \
    themes/dark/rc/checkbox_unchecked_pressed@2x.png \
    themes/dark/rc/line_horizontal.png \
    themes/dark/rc/line_horizontal@2x.png \
    themes/dark/rc/line_horizontal_disabled.png \
    themes/dark/rc/line_horizontal_disabled@2x.png \
    themes/dark/rc/line_horizontal_focus.png \
    themes/dark/rc/line_horizontal_focus@2x.png \
    themes/dark/rc/line_horizontal_pressed.png \
    themes/dark/rc/line_horizontal_pressed@2x.png \
    themes/dark/rc/line_vertical.png \
    themes/dark/rc/line_vertical@2x.png \
    themes/dark/rc/line_vertical_disabled.png \
    themes/dark/rc/line_vertical_disabled@2x.png \
    themes/dark/rc/line_vertical_focus.png \
    themes/dark/rc/line_vertical_focus@2x.png \
    themes/dark/rc/line_vertical_pressed.png \
    themes/dark/rc/line_vertical_pressed@2x.png \
    themes/dark/rc/radio_checked.png \
    themes/dark/rc/radio_checked@2x.png \
    themes/dark/rc/radio_checked_disabled.png \
    themes/dark/rc/radio_checked_disabled@2x.png \
    themes/dark/rc/radio_checked_focus.png \
    themes/dark/rc/radio_checked_focus@2x.png \
    themes/dark/rc/radio_checked_pressed.png \
    themes/dark/rc/radio_checked_pressed@2x.png \
    themes/dark/rc/radio_unchecked.png \
    themes/dark/rc/radio_unchecked@2x.png \
    themes/dark/rc/radio_unchecked_disabled.png \
    themes/dark/rc/radio_unchecked_disabled@2x.png \
    themes/dark/rc/radio_unchecked_focus.png \
    themes/dark/rc/radio_unchecked_focus@2x.png \
    themes/dark/rc/radio_unchecked_pressed.png \
    themes/dark/rc/radio_unchecked_pressed@2x.png \
    themes/dark/rc/toolbar_move_horizontal.png \
    themes/dark/rc/toolbar_move_horizontal@2x.png \
    themes/dark/rc/toolbar_move_horizontal_disabled.png \
    themes/dark/rc/toolbar_move_horizontal_disabled@2x.png \
    themes/dark/rc/toolbar_move_horizontal_focus.png \
    themes/dark/rc/toolbar_move_horizontal_focus@2x.png \
    themes/dark/rc/toolbar_move_horizontal_pressed.png \
    themes/dark/rc/toolbar_move_horizontal_pressed@2x.png \
    themes/dark/rc/toolbar_move_vertical.png \
    themes/dark/rc/toolbar_move_vertical@2x.png \
    themes/dark/rc/toolbar_move_vertical_disabled.png \
    themes/dark/rc/toolbar_move_vertical_disabled@2x.png \
    themes/dark/rc/toolbar_move_vertical_focus.png \
    themes/dark/rc/toolbar_move_vertical_focus@2x.png \
    themes/dark/rc/toolbar_move_vertical_pressed.png \
    themes/dark/rc/toolbar_move_vertical_pressed@2x.png \
    themes/dark/rc/toolbar_separator_horizontal.png \
    themes/dark/rc/toolbar_separator_horizontal@2x.png \
    themes/dark/rc/toolbar_separator_horizontal_disabled.png \
    themes/dark/rc/toolbar_separator_horizontal_disabled@2x.png \
    themes/dark/rc/toolbar_separator_horizontal_focus.png \
    themes/dark/rc/toolbar_separator_horizontal_focus@2x.png \
    themes/dark/rc/toolbar_separator_horizontal_pressed.png \
    themes/dark/rc/toolbar_separator_horizontal_pressed@2x.png \
    themes/dark/rc/toolbar_separator_vertical.png \
    themes/dark/rc/toolbar_separator_vertical@2x.png \
    themes/dark/rc/toolbar_separator_vertical_disabled.png \
    themes/dark/rc/toolbar_separator_vertical_disabled@2x.png \
    themes/dark/rc/toolbar_separator_vertical_focus.png \
    themes/dark/rc/toolbar_separator_vertical_focus@2x.png \
    themes/dark/rc/toolbar_separator_vertical_pressed.png \
    themes/dark/rc/toolbar_separator_vertical_pressed@2x.png \
    themes/dark/rc/transparent.png \
    themes/dark/rc/transparent@2x.png \
    themes/dark/rc/transparent_disabled.png \
    themes/dark/rc/transparent_disabled@2x.png \
    themes/dark/rc/transparent_focus.png \
    themes/dark/rc/transparent_focus@2x.png \
    themes/dark/rc/transparent_pressed.png \
    themes/dark/rc/transparent_pressed@2x.png \
    themes/dark/rc/window_close.png \
    themes/dark/rc/window_close@2x.png \
    themes/dark/rc/window_close_disabled.png \
    themes/dark/rc/window_close_disabled@2x.png \
    themes/dark/rc/window_close_focus.png \
    themes/dark/rc/window_close_focus@2x.png \
    themes/dark/rc/window_close_pressed.png \
    themes/dark/rc/window_close_pressed@2x.png \
    themes/dark/rc/window_grip.png \
    themes/dark/rc/window_grip@2x.png \
    themes/dark/rc/window_grip_disabled.png \
    themes/dark/rc/window_grip_disabled@2x.png \
    themes/dark/rc/window_grip_focus.png \
    themes/dark/rc/window_grip_focus@2x.png \
    themes/dark/rc/window_grip_pressed.png \
    themes/dark/rc/window_grip_pressed@2x.png \
    themes/dark/rc/window_minimize.png \
    themes/dark/rc/window_minimize@2x.png \
    themes/dark/rc/window_minimize_disabled.png \
    themes/dark/rc/window_minimize_disabled@2x.png \
    themes/dark/rc/window_minimize_focus.png \
    themes/dark/rc/window_minimize_focus@2x.png \
    themes/dark/rc/window_minimize_pressed.png \
    themes/dark/rc/window_minimize_pressed@2x.png \
    themes/dark/rc/window_undock.png \
    themes/dark/rc/window_undock@2x.png \
    themes/dark/rc/window_undock_disabled.png \
    themes/dark/rc/window_undock_disabled@2x.png \
    themes/dark/rc/window_undock_focus.png \
    themes/dark/rc/window_undock_focus@2x.png \
    themes/dark/rc/window_undock_pressed.png \
    themes/dark/rc/window_undock_pressed@2x.png \
    themes/darkgood.qss \
    themes/darkgreen.qss \
    themes/darkyellow.qss \
    themes/light/lightstyle.qss \
    themes/light/rc/arrow_down.png \
    themes/light/rc/arrow_down@2x.png \
    themes/light/rc/arrow_down_disabled.png \
    themes/light/rc/arrow_down_disabled@2x.png \
    themes/light/rc/arrow_down_focus.png \
    themes/light/rc/arrow_down_focus@2x.png \
    themes/light/rc/arrow_down_pressed.png \
    themes/light/rc/arrow_down_pressed@2x.png \
    themes/light/rc/arrow_left.png \
    themes/light/rc/arrow_left@2x.png \
    themes/light/rc/arrow_left_disabled.png \
    themes/light/rc/arrow_left_disabled@2x.png \
    themes/light/rc/arrow_left_focus.png \
    themes/light/rc/arrow_left_focus@2x.png \
    themes/light/rc/arrow_left_pressed.png \
    themes/light/rc/arrow_left_pressed@2x.png \
    themes/light/rc/arrow_right.png \
    themes/light/rc/arrow_right@2x.png \
    themes/light/rc/arrow_right_disabled.png \
    themes/light/rc/arrow_right_disabled@2x.png \
    themes/light/rc/arrow_right_focus.png \
    themes/light/rc/arrow_right_focus@2x.png \
    themes/light/rc/arrow_right_pressed.png \
    themes/light/rc/arrow_right_pressed@2x.png \
    themes/light/rc/arrow_up.png \
    themes/light/rc/arrow_up@2x.png \
    themes/light/rc/arrow_up_disabled.png \
    themes/light/rc/arrow_up_disabled@2x.png \
    themes/light/rc/arrow_up_focus.png \
    themes/light/rc/arrow_up_focus@2x.png \
    themes/light/rc/arrow_up_pressed.png \
    themes/light/rc/arrow_up_pressed@2x.png \
    themes/light/rc/base_icon.png \
    themes/light/rc/base_icon@2x.png \
    themes/light/rc/base_icon_disabled.png \
    themes/light/rc/base_icon_disabled@2x.png \
    themes/light/rc/base_icon_focus.png \
    themes/light/rc/base_icon_focus@2x.png \
    themes/light/rc/base_icon_pressed.png \
    themes/light/rc/base_icon_pressed@2x.png \
    themes/light/rc/branch_closed.png \
    themes/light/rc/branch_closed@2x.png \
    themes/light/rc/branch_closed_disabled.png \
    themes/light/rc/branch_closed_disabled@2x.png \
    themes/light/rc/branch_closed_focus.png \
    themes/light/rc/branch_closed_focus@2x.png \
    themes/light/rc/branch_closed_pressed.png \
    themes/light/rc/branch_closed_pressed@2x.png \
    themes/light/rc/branch_end.png \
    themes/light/rc/branch_end@2x.png \
    themes/light/rc/branch_end_disabled.png \
    themes/light/rc/branch_end_disabled@2x.png \
    themes/light/rc/branch_end_focus.png \
    themes/light/rc/branch_end_focus@2x.png \
    themes/light/rc/branch_end_pressed.png \
    themes/light/rc/branch_end_pressed@2x.png \
    themes/light/rc/branch_line.png \
    themes/light/rc/branch_line@2x.png \
    themes/light/rc/branch_line_disabled.png \
    themes/light/rc/branch_line_disabled@2x.png \
    themes/light/rc/branch_line_focus.png \
    themes/light/rc/branch_line_focus@2x.png \
    themes/light/rc/branch_line_pressed.png \
    themes/light/rc/branch_line_pressed@2x.png \
    themes/light/rc/branch_more.png \
    themes/light/rc/branch_more@2x.png \
    themes/light/rc/branch_more_disabled.png \
    themes/light/rc/branch_more_disabled@2x.png \
    themes/light/rc/branch_more_focus.png \
    themes/light/rc/branch_more_focus@2x.png \
    themes/light/rc/branch_more_pressed.png \
    themes/light/rc/branch_more_pressed@2x.png \
    themes/light/rc/branch_open.png \
    themes/light/rc/branch_open@2x.png \
    themes/light/rc/branch_open_disabled.png \
    themes/light/rc/branch_open_disabled@2x.png \
    themes/light/rc/branch_open_focus.png \
    themes/light/rc/branch_open_focus@2x.png \
    themes/light/rc/branch_open_pressed.png \
    themes/light/rc/branch_open_pressed@2x.png \
    themes/light/rc/checkbox_checked.png \
    themes/light/rc/checkbox_checked@2x.png \
    themes/light/rc/checkbox_checked_disabled.png \
    themes/light/rc/checkbox_checked_disabled@2x.png \
    themes/light/rc/checkbox_checked_focus.png \
    themes/light/rc/checkbox_checked_focus@2x.png \
    themes/light/rc/checkbox_checked_pressed.png \
    themes/light/rc/checkbox_checked_pressed@2x.png \
    themes/light/rc/checkbox_indeterminate.png \
    themes/light/rc/checkbox_indeterminate@2x.png \
    themes/light/rc/checkbox_indeterminate_disabled.png \
    themes/light/rc/checkbox_indeterminate_disabled@2x.png \
    themes/light/rc/checkbox_indeterminate_focus.png \
    themes/light/rc/checkbox_indeterminate_focus@2x.png \
    themes/light/rc/checkbox_indeterminate_pressed.png \
    themes/light/rc/checkbox_indeterminate_pressed@2x.png \
    themes/light/rc/checkbox_unchecked.png \
    themes/light/rc/checkbox_unchecked@2x.png \
    themes/light/rc/checkbox_unchecked_disabled.png \
    themes/light/rc/checkbox_unchecked_disabled@2x.png \
    themes/light/rc/checkbox_unchecked_focus.png \
    themes/light/rc/checkbox_unchecked_focus@2x.png \
    themes/light/rc/checkbox_unchecked_pressed.png \
    themes/light/rc/checkbox_unchecked_pressed@2x.png \
    themes/light/rc/line_horizontal.png \
    themes/light/rc/line_horizontal@2x.png \
    themes/light/rc/line_horizontal_disabled.png \
    themes/light/rc/line_horizontal_disabled@2x.png \
    themes/light/rc/line_horizontal_focus.png \
    themes/light/rc/line_horizontal_focus@2x.png \
    themes/light/rc/line_horizontal_pressed.png \
    themes/light/rc/line_horizontal_pressed@2x.png \
    themes/light/rc/line_vertical.png \
    themes/light/rc/line_vertical@2x.png \
    themes/light/rc/line_vertical_disabled.png \
    themes/light/rc/line_vertical_disabled@2x.png \
    themes/light/rc/line_vertical_focus.png \
    themes/light/rc/line_vertical_focus@2x.png \
    themes/light/rc/line_vertical_pressed.png \
    themes/light/rc/line_vertical_pressed@2x.png \
    themes/light/rc/radio_checked.png \
    themes/light/rc/radio_checked@2x.png \
    themes/light/rc/radio_checked_disabled.png \
    themes/light/rc/radio_checked_disabled@2x.png \
    themes/light/rc/radio_checked_focus.png \
    themes/light/rc/radio_checked_focus@2x.png \
    themes/light/rc/radio_checked_pressed.png \
    themes/light/rc/radio_checked_pressed@2x.png \
    themes/light/rc/radio_unchecked.png \
    themes/light/rc/radio_unchecked@2x.png \
    themes/light/rc/radio_unchecked_disabled.png \
    themes/light/rc/radio_unchecked_disabled@2x.png \
    themes/light/rc/radio_unchecked_focus.png \
    themes/light/rc/radio_unchecked_focus@2x.png \
    themes/light/rc/radio_unchecked_pressed.png \
    themes/light/rc/radio_unchecked_pressed@2x.png \
    themes/light/rc/toolbar_move_horizontal.png \
    themes/light/rc/toolbar_move_horizontal@2x.png \
    themes/light/rc/toolbar_move_horizontal_disabled.png \
    themes/light/rc/toolbar_move_horizontal_disabled@2x.png \
    themes/light/rc/toolbar_move_horizontal_focus.png \
    themes/light/rc/toolbar_move_horizontal_focus@2x.png \
    themes/light/rc/toolbar_move_horizontal_pressed.png \
    themes/light/rc/toolbar_move_horizontal_pressed@2x.png \
    themes/light/rc/toolbar_move_vertical.png \
    themes/light/rc/toolbar_move_vertical@2x.png \
    themes/light/rc/toolbar_move_vertical_disabled.png \
    themes/light/rc/toolbar_move_vertical_disabled@2x.png \
    themes/light/rc/toolbar_move_vertical_focus.png \
    themes/light/rc/toolbar_move_vertical_focus@2x.png \
    themes/light/rc/toolbar_move_vertical_pressed.png \
    themes/light/rc/toolbar_move_vertical_pressed@2x.png \
    themes/light/rc/toolbar_separator_horizontal.png \
    themes/light/rc/toolbar_separator_horizontal@2x.png \
    themes/light/rc/toolbar_separator_horizontal_disabled.png \
    themes/light/rc/toolbar_separator_horizontal_disabled@2x.png \
    themes/light/rc/toolbar_separator_horizontal_focus.png \
    themes/light/rc/toolbar_separator_horizontal_focus@2x.png \
    themes/light/rc/toolbar_separator_horizontal_pressed.png \
    themes/light/rc/toolbar_separator_horizontal_pressed@2x.png \
    themes/light/rc/toolbar_separator_vertical.png \
    themes/light/rc/toolbar_separator_vertical@2x.png \
    themes/light/rc/toolbar_separator_vertical_disabled.png \
    themes/light/rc/toolbar_separator_vertical_disabled@2x.png \
    themes/light/rc/toolbar_separator_vertical_focus.png \
    themes/light/rc/toolbar_separator_vertical_focus@2x.png \
    themes/light/rc/toolbar_separator_vertical_pressed.png \
    themes/light/rc/toolbar_separator_vertical_pressed@2x.png \
    themes/light/rc/transparent.png \
    themes/light/rc/transparent@2x.png \
    themes/light/rc/transparent_disabled.png \
    themes/light/rc/transparent_disabled@2x.png \
    themes/light/rc/transparent_focus.png \
    themes/light/rc/transparent_focus@2x.png \
    themes/light/rc/transparent_pressed.png \
    themes/light/rc/transparent_pressed@2x.png \
    themes/light/rc/window_close.png \
    themes/light/rc/window_close@2x.png \
    themes/light/rc/window_close_disabled.png \
    themes/light/rc/window_close_disabled@2x.png \
    themes/light/rc/window_close_focus.png \
    themes/light/rc/window_close_focus@2x.png \
    themes/light/rc/window_close_pressed.png \
    themes/light/rc/window_close_pressed@2x.png \
    themes/light/rc/window_grip.png \
    themes/light/rc/window_grip@2x.png \
    themes/light/rc/window_grip_disabled.png \
    themes/light/rc/window_grip_disabled@2x.png \
    themes/light/rc/window_grip_focus.png \
    themes/light/rc/window_grip_focus@2x.png \
    themes/light/rc/window_grip_pressed.png \
    themes/light/rc/window_grip_pressed@2x.png \
    themes/light/rc/window_minimize.png \
    themes/light/rc/window_minimize@2x.png \
    themes/light/rc/window_minimize_disabled.png \
    themes/light/rc/window_minimize_disabled@2x.png \
    themes/light/rc/window_minimize_focus.png \
    themes/light/rc/window_minimize_focus@2x.png \
    themes/light/rc/window_minimize_pressed.png \
    themes/light/rc/window_minimize_pressed@2x.png \
    themes/light/rc/window_undock.png \
    themes/light/rc/window_undock@2x.png \
    themes/light/rc/window_undock_disabled.png \
    themes/light/rc/window_undock_disabled@2x.png \
    themes/light/rc/window_undock_focus.png \
    themes/light/rc/window_undock_focus@2x.png \
    themes/light/rc/window_undock_pressed.png \
    themes/light/rc/window_undock_pressed@2x.png
