#include "omarchytheme.h"

#include <algorithm>

#include <QColor>
#include <QDir>
#include <QFile>
#include <QMap>
#include <QRegularExpression>
#include <QTextStream>

namespace {

bool g_isDark = true;

QString omarchyColorsFilePath()
{
    QString stateHome = qEnvironmentVariable("XDG_STATE_HOME");
    if (stateHome.isEmpty()) {
        stateHome = QDir::homePath() + "/.local/state";
    }
    return stateHome + "/omarchy/current/theme/colors.toml";
}

// Omarchy normalizes every active theme into a flat colors.toml with plain
// `key = "#rrggbb"` lines (background, foreground, accent, selection,
// color0..color15). We only need to pick the hex-color lines out of it.
QMap<QString, QColor> parseOmarchyColors(const QString& path)
{
    QMap<QString, QColor> result;

    QFile file(path);
    if (!file.open(QFile::ReadOnly | QFile::Text)) {
        return result;
    }

    static const QRegularExpression lineRe(QStringLiteral(R"re(^\s*([A-Za-z0-9_]+)\s*=\s*"(#[0-9A-Fa-f]{6})")re"));

    QTextStream ts(&file);
    while (!ts.atEnd()) {
        const QRegularExpressionMatch m = lineRe.match(ts.readLine());
        if (m.hasMatch()) {
            result.insert(m.captured(1), QColor(m.captured(2)));
        }
    }
    return result;
}

double relativeLuma(const QColor& c)
{
    return 0.2126 * c.redF() + 0.7152 * c.greenF() + 0.0722 * c.blueF();
}

QColor blend(const QColor& from, const QColor& to, double t)
{
    t = std::clamp(t, 0.0, 1.0);
    return QColor::fromRgbF(
        from.redF()   + (to.redF()   - from.redF())   * t,
        from.greenF() + (to.greenF() - from.greenF()) * t,
        from.blueF()  + (to.blueF()  - from.blueF())  * t
    );
}

} // namespace

namespace OmarchyTheme {

bool isAvailable()
{
    return QFile::exists(omarchyColorsFilePath());
}

bool isDark()
{
    return g_isDark;
}

QString styleSheet()
{
    const QMap<QString, QColor> raw = parseOmarchyColors(omarchyColorsFilePath());

    if (!raw.contains("background") || !raw.contains("foreground") || !raw.contains("accent")) {
        return QString();
    }

    const QColor background = raw.value("background");
    const QColor foreground = raw.value("foreground");
    const QColor accent = raw.value("accent");
    const QColor selection = raw.value("selection", blend(background, accent, 0.4));

    g_isDark = relativeLuma(background) < 0.5;
    const QColor extreme = g_isDark ? QColor(Qt::black) : QColor(Qt::white);

    // Derived UI-chrome shades: Omarchy only publishes a handful of semantic
    // colors, so the rest of the widget palette is generated by blending
    // background/foreground/accent, the same way omarchy-theme-set-templates
    // mixes colors for other apps' themed configs.
    const QColor field             = blend(background, extreme, 0.35);
    const QColor fieldAlt          = blend(field, foreground, 0.06);
    const QColor panel             = blend(background, foreground, 0.10);
    const QColor panelAlt          = blend(background, foreground, 0.16);
    const QColor panelHover        = blend(background, foreground, 0.28);
    const QColor disabledText      = blend(foreground, background, 0.5);
    const QColor handle            = blend(foreground, background, 0.55);
    const QColor handleLight       = blend(foreground, background, 0.35);
    const QColor selectionDisabled = blend(selection, background, 0.5);
    const QColor accentBright      = blend(accent, foreground, 0.3);

    QFile templateFile(QStringLiteral(":/themes/omarchy/omarchystyle.qss.tpl"));
    if (!templateFile.open(QFile::ReadOnly | QFile::Text)) {
        return QString();
    }

    QString qss = QString::fromUtf8(templateFile.readAll());

    const QMap<QString, QColor> tokens{
        {"background", background},
        {"foreground", foreground},
        {"accent", accent},
        {"accentBright", accentBright},
        {"selection", selection},
        {"selectionDisabled", selectionDisabled},
        {"field", field},
        {"fieldAlt", fieldAlt},
        {"panel", panel},
        {"panelAlt", panelAlt},
        {"panelHover", panelHover},
        {"disabledText", disabledText},
        {"handle", handle},
        {"handleLight", handleLight},
    };

    for (auto it = tokens.constBegin(); it != tokens.constEnd(); ++it) {
        qss.replace(QStringLiteral("{{%1}}").arg(it.key()), it.value().name(QColor::HexRgb));
    }

    return qss;
}

} // namespace OmarchyTheme
